---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: petclinic-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        env1: dev
        app: petclinic
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: petclinic
        image: snaidu/petclinic:1
        imagePullPolicy: "Always"
        ports:
          - containerPort: 8080
            protocol: TCP
