---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-svc
  namespace: petclinic-dev
spec:
  selector:
    env1: dev
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30003
  type: LoadBalancer